version: '3'
services:
        web:
                image: alaat_port_v1
                build: .
                ports:
                        - "8812:8812"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
